[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "ai-resume-analyzer2.streamlit.app"
